iHouse/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace iHouse.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }
    }
}

iHouse/Controllers/PropertyController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using iHouse.Models;

namespace iHouse.Controllers
{
    public class PropertyController : Controller
    {
        // GET: Property/Index
        [HttpGet]
        public ActionResult Index()
        {
            iHouseEntities entities = new iHouseEntities();
            ViewBag.List = entities.Houses.OrderByDescending(x => x.HouseId).ToList();
            return View();
        }

        //Post: Property/Index
        [HttpPost]
        public ActionResult Index(string Region, string Suburb, string Type)
        {
            if (Region == null && Suburb== null && Type == null)
            {
                TempData["SeachFailed"] = "Please input at least one search condition";
                return View();
            }
            iHouseEntities entities = new iHouseEntities();
            List<House> SearchResult = entities.Houses
                                        .Where(x => x.Region.Contains(Region) & x.Suburb.Contains(Suburb) & x.Type.Contains(Type))
                                        .OrderByDescending(x => x.HouseId)
                                        .ToList();
            ViewBag.List = SearchResult;
            return View();
        }


    }
}

iHouse/Controllers/SellerController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using iHouse.Models;

namespace iHouse.Controllers
{
    public class SellerController : Controller
    {
        private iHouseEntities entities = new iHouseEntities();
        // GET: Seller/Index
        public ActionResult Index()
        {
            
            return View();

        }
      

        // POST: Seller/Register
        [HttpPost]
        public ActionResult Register(Seller seller)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    
                    entities.Sellers.Add(seller);
                    entities.SaveChanges();

                    //Success acknowledge message
                    TempData["SuccessMsg"] = "Successfully registered";

                    return RedirectToAction("Me", "MyProperty", new { SellerId = seller.SellerId});
                }
                catch
                {
                    return View("Index");
                }

            }
            return View("Index");
        }


        // GET: Seller/Update/SellerId=5
        public ActionResult Update(int? SellerId)
        {
            if (SellerId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Seller seller = entities.Sellers.Find(SellerId);
            if (seller == null)
            {
                return HttpNotFound();
            }
            return View(seller);

        }

        //POST: Seller/Update/SellerId=5
        [HttpPost]
        public ActionResult Update(int? SellerId, Seller seller)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    
                    entities.Entry(seller).State = EntityState.Modified;
                    entities.SaveChanges();

                    //acknowledge message
                    TempData["SuccessMsg"] = "Your information has been successfully updated";

                    return RedirectToAction("Me", "MyProperty", new { SellerId = seller.SellerId});
                }
                catch
                {
                    return View();
                }
            }
            return View();

        }

    }
}

iHouse/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
}

    <div style="text-align:center; padding:50px">
        <h3>Sellers sell more, buyers spend less</h3>
        <P>Millions of real-time house information</P>
        <p>We've become one of New Zealand's most well known and respected property trading platforms. Our name has become synonymous with uncompromised quality and service, and our entire network is committed to the continuous improvement of the services we offer.</p>
        <a href="@Url.Action("Index","Seller")"><img src="/Content/Images/Register.png" width="200"/></a>
    </div>

    <a href="@Url.Action("Index","Property")" style="display:block; height:300px; background:#fafafa; padding:20px">
        <div style="width:50%; height:100%; background-image:url(/Content/Images/house2.jpg);  background-size:cover; background-position-y:center; float:left">

        </div>

        <div style="width:50%; height:100%; margin:auto; padding:100px; float:left">
            <h4>Property Market</h4>
            <p>Find the best and cheapest house</p>
        </div>
    </a>

    <a href="@Url.Action("Index", "MyProperty")" style="display:block; height:300px; padding:20px">
        <div style="width:50%; height:100%; text-align:right; margin:auto; padding:100px; float:left">
            <h4>Sell your house</h4>
            <p>Make your property more welcome</p>
        </div>

        <div style="width:50%; height:100%; float:left; background-image:url(/Content/Images/house1.jpg); background-size:cover;  background-position-y:center">

        </div>
    </a>